name: Deploy to Firebase
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn setup
      - name: Init Firebase Functions config
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set github.gh_token="${{ secrets.GH_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:libraries
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
